### ISSUE TITLE
trying to see new messages

### ISSUE THREAD

**Issue by Valentyn-Kubrak** [Slava/meteor-gmail#1]
Sorry, I can not understand where I should to obtain new messages from example by using console.log?. And in what file I should to put code from example, in template manager?

I also   added

``` javascript
     gmailClients[doc._id].onNewEmail('subject:test', function (message) {
        Msgs.insert({
          "msg": message.snippet,
          "to": message.to,
          "from" : message.from,
          "object" : message.subject
        })
      });
```

But I can't receive any new item in collection after sending new message

**Comment by Valentyn-Kubrak** [comment]
Or please, tell me, Slava, how to get new 20 messages for example. I successfully logged in my local app by using google account, I just want to retrieve current new 20 messages.

**Comment by Slava** [comment]
Hmm, sorry for getting so late to this. To be honest, I didn't even notice this issue. Did you try looking at the example app? https://github.com/Slava/meteor-gmail/tree/master/example

**Comment by Slava** [comment]
Gonna close this as it's been a while with no response.
